version: "3"
services:
  blog_php_fpm:
    build: docker/php_fpm
    image: blog_php_fpm:latest
    labels:
      com.datadoghq.ad.logs: '[{"source": "nginx", "service": "blog_phpfpm"}]'
    volumes:
      - .:/var/www
    restart: always
  blog_php_fpm_debug:
    build: docker/php_fpm_debug
    depends_on:
      - blog_php_fpm
    labels:
      com.datadoghq.ad.logs: '[{"source": "nginx", "service": "blog_phpfpm_debug"}]'
    volumes:
      - .:/var/www
    restart: always
  nginx:
    build: docker/nginx
    depends_on:
      - blog_php_fpm
    labels:
      com.datadoghq.ad.logs: '[{"source": "nginx", "service": "blog_nginx"}]'
    volumes:
      - .:/var/www
    restart: always
