version: "3"
services:
  blog_php_fpm:
    build: docker/php_fpm
    image: blog_php_fpm:latest
    volumes:
      - .:/var/www
    restart: always
  blog_php_fpm_debug:
    build: docker/php_fpm_debug
    depends_on:
      - blog_php_fpm
    volumes:
      - .:/var/www
    restart: always
  installer:
    build: docker/installer
    environment:
      - COMPOSER_CACHE_DIR=/var/app/var/cache/composer
      - COMPOSER_ALLOW_SUPERUSER=1
    volumes:
      - .:/var/app
  nginx:
    build: docker/nginx
    depends_on:
      - blog_php_fpm
    volumes:
      - .:/var/www
    restart: always
