language: c
install:
    - sudo apt-get update -qq
    - sudo apt-get install -q vim-common file libffi6 libgmp10
    - curl -L "http://archive.ubuntu.com/ubuntu/pool/universe/s/shellcheck/shellcheck_0.3.7-1_amd64.deb" -o "/tmp/shellcheck_0.3.7-1_amd64.deb"
    - '[ "$(openssl dgst -sha256 "/tmp/shellcheck_0.3.7-1_amd64.deb" | cut -d " " -f 2)" == "1622b0ebead82475946188c7ace2afe012607c1b064d2888556f296a28cd1927" ]'
    - sudo dpkg -i "/tmp/shellcheck_0.3.7-1_amd64.deb"
script: make && make test SHELL="bash -x"
